### ISSUE TITLE
Replace requires to root `env.js`

### ISSUE THREAD

**Issue by medikoo** [egovernment/eregistrations#1746]
`env.js` as in root is optional file, and should never be required by any modules. instead it's `server/env.js` that should be required.

It looks that with Super User improvements we've introduced a bug of requiring this file directly, as reported here: https://github.com/egovernment/eregistrations-guatemala/pull/925#issuecomment-272675272

Let's fix it in all systems

**Comment by kamsi** [comment]
@medikoo All the end systems have been updated (ELS, GT, TZ)
